services:
    - type: web
      env: node
      name: fp-prod-backend1
      repo: https://github.com/ShamanthOP/forms_processor.git
      buildFilter:
          paths:
              - apps/backend/**
      buildCommand: npm install && cd apps/backend && npm install && cd ../../ && npm run build:backend
      startCommand: cd apps/backend; npm run start
      plan: free
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: fp-prod-db1
                property: connectionString
          - key: REDIS_URL
            fromService:
                name: fp-prod-redis1
                type: redis
                property: connectionString

    - type: web
      env: static
      name: fp-prod-frontend1
      repo: https://github.com/ShamanthOP/forms_processor.git
      buildFilter:
          paths:
              - apps/frontend/**
      buildCommand: npm install && cd apps/frontend && npm install && cd ../../ && npm run build:frontend && cd apps/frontend && npm run db:migrate
      staticPublishPath: ./apps/frontend/build
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
      envVars:
          - key: REACT_APP_GRAPHQL_HOST
            fromService:
                name: fp-prod-backend1
                type: web
                property: host

    - type: redis
      name: fp-prod-redis1
      plan: free
      ipAllowList: []

databases:
    - name: fp-prod-db1
      plan: free
